# Utiliza una imagen base de Zulu OpenJDK en Alpine
# Inspirado en: https://stackoverflow.com/questions/53669151/java-11-application-as-lightweight-docker-image/57145029#57145029
FROM azul/zulu-openjdk-alpine:11 as packager

RUN { \
        java --version ; \
        echo "jlink version:" && \
        jlink --version ; \
    }

ENV JAVA_MINIMAL=/opt/jre

# Construye una distribución mínima de módulos
RUN jlink \
    --verbose \
    --add-modules \
        java.base,java.sql,java.naming,java.desktop,java.management,java.security.jgss,java.instrument \
    --compress 2 \
    --strip-debug \
    --no-header-files \
    --no-man-pages \
    --output "$JAVA_MINIMAL"

# Segunda etapa, poner lo minimo para ejecutar el .jar y agregar el curl
FROM alpine
ENV JAVA_MINIMAL=/opt/jre
ENV PATH="$PATH:$JAVA_MINIMAL/bin"

# Instala curl
RUN apk --no-cache add curl

# Directorio para el .jar
WORKDIR /app

# Fix java test angelo
ENV JAVA_HOME=/opt/jre

# Clona solo el archivo microservicio_java.jar desde mi rama "java"
RUN curl -LJO https://github.com/AngeloLaMadrid/MicroServicio/raw/java/microservicio_java.jar

# Comando para ejecutar el archivo .jar
CMD ["java", "-jar", "microservicio_java.jar"]
