# Utiliza la imagen base Alpine con OpenJDK 11
FROM alpine:3.14

# Etiqueta del Dockerfile
LABEL maintainer="02_AngeloLaMadrid_JAVA"

# Actualizar el sistema e instala curl y OpenJDK 11
RUN apk update && apk add --no-cache curl openjdk11-jre

# Crea una carpeta llamada "Microservicio" en el escritorio
RUN mkdir -p /root/Desktop/Microservicio

# Clona solo la rama "java" y los archivos necesarios desde GitHub en la carpeta "Microservicio"
RUN apk add --no-cache git && \
    git clone --depth 1 -b java --single-branch https://github.com/AngeloLaMadrid/MicroServicio.git /root/Desktop/Microservicio && \
    rm -rf /root/Desktop/Microservicio/.git

# Establece el directorio de trabajo dentro de la imagen
WORKDIR /root/Desktop/Microservicio

# Comando predeterminado para ejecutar cuando se inicia el contenedor
CMD ["java", "-jar", "microservicio_java.jar"]
