# Utiliza la imagen base Alpine con OpenJDK
FROM alpine:3.14

# Etiqueta del Dockerfile
LABEL maintainer="02_AngeloLaMadrid_JAVA"

# Actualiza el sistema e instala OpenJDK 11 y curl
RUN apk update && apk add --no-cache openjdk11-jre curl

# Establece el directorio para el .jar
WORKDIR /app

# Fix java test angelo
ENV JAVA_HOME=/opt/jre

# Clonar solo el archivo microservicio_java.jar desde mi rama "java"
RUN apk add --no-cache git && \
    curl -LJO https://github.com/AngeloLaMadrid/MicroServicio/raw/java/microservicio_java.jar

# Comando para ejecutar el archivo .jar 
CMD ["java", "-jar", "microservicio_java.jar"]
