# Creditos: AngeloLaMadrid
# Repositorio: AngeloLaMadrid/DockerfileLiviano-JAVA-PYTHON-ANGULAR

# Instrucciones-----------------------------------------------------------------
# En este EJEMPLO tengo mi jar con el nombre "backend-old.jar" de puerto 8090 (cambiarlos al suyo), deben hacer los pasos:
# 1.-Cambiar por el nombre de su IMAGEN en las lineas: 43 y 49
# 2.-Cambiar el PUERTO al suyo en la linea: 46

# Etapa de construccion
FROM eclipse-temurin:17-jdk-alpine as packager

# Construir distribucion minima de modulos
RUN jlink \
    --verbose \
    --add-modules java.base,java.sql,java.naming,java.management,java.instrument,java.desktop \
    --compress 2 \
    --strip-debug \
    --no-header-files \
    --no-man-pages \
    --output /opt/jre

# Segunda etapa, configurar entorno minimo
FROM alpine:latest

# Instalar dependencias necesarias para ejecutar Java
RUN apk add --no-cache libc6-compat

# Copiar JRE personalizado desde la etapa de construccion
COPY --from=packager /opt/jre /opt/jre

# Configuracion del entorno y del PATH
ENV JAVA_HOME=/opt/jre
ENV PATH=$PATH:$JAVA_HOME/bin

# Directorio de trabajo para el JAR
WORKDIR /app

# Copiar el JAR (renombrar por el nombre de su jar) ***
COPY backend-old.jar .

# Exponer el puerto 8090 (cambiar si es necesario)
EXPOSE 8090

# Comando de inicio, IMPORTANTE renombrar el jar si tiene otro nombre ***
CMD ["java", "-jar", "backend-old.jar"]

# Imagen y Contenedor-------------------------------------------------
# Cambiar el nombre de la imagen y el puerto (si es necesario)
# docker build -t angelolm/backend-old .
# docker run -d --name contenedor -p 8090:8090 angelolm/backend-old



